config/routes.rb
Rails.application.routes.draw do
  resources :min_maxes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/min_max.rb
class MinMax < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/min_maxes_controller.rb
class MinMaxesController < ApplicationController
  before_action :set_min_max, only: %i[ show edit update destroy ]

  # GET /min_maxes or /min_maxes.json
  def index
    @min_maxes = MinMax.all
  end

  # GET /min_maxes/1 or /min_maxes/1.json
  def show
  end

  # GET /min_maxes/new
  def new
    @min_max = MinMax.new
  end

  # GET /min_maxes/1/edit
  def edit
  end

  # POST /min_maxes or /min_maxes.json
  def create
    @min_max = MinMax.new(min_max_params)

    respond_to do |format|
      if @min_max.save
        format.html { redirect_to @min_max, notice: "Min max was successfully created." }
        format.json { render :show, status: :created, location: @min_max }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @min_max.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /min_maxes/1 or /min_maxes/1.json
  def update
    respond_to do |format|
      if @min_max.update(min_max_params)
        format.html { redirect_to @min_max, notice: "Min max was successfully updated." }
        format.json { render :show, status: :ok, location: @min_max }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @min_max.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /min_maxes/1 or /min_maxes/1.json
  def destroy
    @min_max.destroy
    respond_to do |format|
      format.html { redirect_to min_maxes_url, notice: "Min max was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_min_max
      @min_max = MinMax.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def min_max_params
      params.require(:min_max).permit(:user, :attempts, :target)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/min_maxes_helper.rb
module MinMaxesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Discord</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/min_maxes/_form.html.erb
<%= form_with(model: min_max) do |form| %>
  <% if min_max.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(min_max.errors.count, "error") %> prohibited this min_max from being saved:</h2>

      <ul>
        <% min_max.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user %>
    <%= form.text_field :user %>
  </div>

  <div class="field">
    <%= form.label :attempts %>
    <%= form.number_field :attempts %>
  </div>

  <div class="field">
    <%= form.label :target %>
    <%= form.number_field :target %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/min_maxes/edit.html.erb
<h1>Editing Min Max</h1>

<%= render 'form', min_max: @min_max %>

<%= link_to 'Show', @min_max %> |
<%= link_to 'Back', min_maxes_path %>

app/views/min_maxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Min Maxes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Attempts</th>
      <th>Target</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @min_maxes.each do |min_max| %>
      <tr>
        <td><%= min_max.user %></td>
        <td><%= min_max.attempts %></td>
        <td><%= min_max.target %></td>
        <td><%= link_to 'Show', min_max %></td>
        <td><%= link_to 'Edit', edit_min_max_path(min_max) %></td>
        <td><%= link_to 'Destroy', min_max, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Min Max', new_min_max_path %>

app/views/min_maxes/new.html.erb
<h1>New Min Max</h1>

<%= render 'form', min_max: @min_max %>

<%= link_to 'Back', min_maxes_path %>

app/views/min_maxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @min_max.user %>
</p>

<p>
  <strong>Attempts:</strong>
  <%= @min_max.attempts %>
</p>

<p>
  <strong>Target:</strong>
  <%= @min_max.target %>
</p>

<%= link_to 'Edit', edit_min_max_path(@min_max) %> |
<%= link_to 'Back', min_maxes_path %>